### ISSUE TITLE
Test Issue for GitHub for MS Teams 

### ISSUE THREAD

**Issue by kozlowskik** [CS305-F18-TeamDOS/Gradebook#14]
This is just a test issue that will be resolved when done testing the MS Teams GitHub Plugin

**Comment by kozlowskik** [comment]
test comment

**Comment by kozlowskik** [comment]
another testing comment

**Comment by JoeTether** [comment]
Commenting from MS teams.

**Comment by bella004** [comment]
Test comment

**Comment by kozlowskik** [comment]
Finished testing the MS Teams Github notifications
