### ISSUE TITLE
Conceptual Schema, Logical Schema, and Physical Schema do not reflect each other well

### ISSUE THREAD

**Issue by bella004** [CS305-F18-TeamDOS/Gradebook#2]
It appears that the physical schema has attributes that the conceptual and logical schemas do not e.g. `Gradebook.Grade` has `GPA` but the ER diagram does not.
Also from what @JoeTether said in Teams, the relationships in the ER do not have names yet the logical schema gives them names.
I suggest that the conceptual and logical schemas be revised to reflect the physical schema as this schema has more attributes to work with, though I'm open to removing attributes in the physical schema as some do seem a bit redundant, at first glace e.g. `YearEnrolled` and `DateEnrolled` in `Gradebook.Enrollee` are kind of the same thing.

**Comment by JoeTether** [comment]
I agree, I think we should simplify the physical schema to reflect the optimized schema.

**Comment by JoeTether** [comment]
This issue was addressed in the Schema consistency update branch, and the changes have been merged. #7
